---
- hosts: all
  become: yes

  tasks:

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade installed packages
      apt:
        upgrade: dist

    - name: Remove unnecessary packages
      apt:
        autoremove: yes

    - name: Clean downloaded packages
      apt:
        autoclean: yes
